service: test

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:022015240694:table/ItemTable

functions:
  addItem:
    handler: src/addItem.addItem
    events:
      - httpApi:
          path: /items
          method: post
  getItems:
    handler: src/getItems.getItems
    events:
      - httpApi:
          path: /items
          method: get
  getItem:
    handler: src/getItem.getItem
    events:
      - httpApi:
          path: /items/{id}
          method: get
  updateItem:
    handler: src/updateItem.updateItem
    events:
      - httpApi:
          path: /items/{id}
          method: put
  deleteItem:
    handler: src/deleteItem.deleteItem
    events:
      - httpApi:
          path: /items/{id}
          method: delete       

resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTable
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1